# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ruby_questions = ["What is the difference between a class and a module?",
"What is an object?",
"How would you declare and use a constructor in Ruby?",
"How would you create getter and setter methods in Ruby?",
"Describe the difference between class and instance variables?",
"What are the three levels of method access control for classes and what do they signify?",
"What does ‘self’ mean?",
"Explain how (almost) everything is an object in Ruby.",
"Explain what singleton methods are. What is Eigenclass in Ruby?",
"Describe Ruby method lookup path.",
"Describe available Ruby callbacks. How can we use them in practice?",
"What is the difference between Proc and lambda?",
"What is Rack?",
"Explain the Rack application interface.",
"Write a simple Rack application.",
"How does Rack middleware works?",
"What is RubyGems? How does it work?",
"How can you build your own Ruby gem?",
"Explain the structure of a Ruby gem.",
"Can you give me some examples of your favorite gems besides Ruby on Rails?",
"What is ActiveJob? When should we use it?",
"What is Asset Pipeline?",
"Explain the difference between Page, Action, Fragment, Low-Level, SQL caching types.",
"What is a Rails engine?",
"Provide an example of RESTful routing and controller.",
"Describe CRUD verbs and actions.",
"How should you test routes?",
"How should you use filters in controllers?",
"What are Strong Parameters?",
"What do we need to test in controllers?",
"How should you use content_for and yield?",
"How should you use nested layouts?",
"Explain the Active Record pattern.",
"What is Object-Relational Mapping?",
"Describe Active Record conventions.",
"Explain the Migrations mechanism.",
"Describe types of associations in Active Record.",
"What is Scopes? How should you use it?",
"Explain the difference between optimistic and pessimistic locking.",
"Explain what is a sessions mechanism. How does it work?",
"Describe cross-site request forgery, cross-site scripting, session hijacking, and session fixation attacks.",
"What is the difference between SQL Injection and CSS Injection?",
"How should you store secure data such as a password?",
"Why do we need to use HTTPS instead of HTTP?",
"What is unit testing (in classical terms)?",
"What is the primary technique for writing a test?",
"What are your favorite tools for writing unit tests?",
"What are your favorite tools for writing feature tests?",
"What is a code smell?",
"What are your favorite tools to find code smells and potential bugs?",
"Why should you avoid fat controllers?",
"Why should you avoid fat models?",
"Explain extract Value, Service, Form, View, Query, and Policy Objects techniques."]


javascript_questions = [
"What is JavaScript?",
"Enumerate the differences between Java and JavaScript?",
"What are JavaScript Data Types?",
"What is the use of isNaN function?",
"Between JavaScript and an ASP script, which is faster?",
"What is negative infinity?",
"Is it possible to break JavaScript Code into several lines?",
"Which company developed JavaScript?",
"What are undeclared and undefined variables?",
"Write the code for adding new elements dynamically?",
"What are global variables? How are these variable declared and what are the problems associated with using them?",
"What is a prompt box?",
"What is 'this' keyword in JavaScript?",
"Explain the working of timers in JavaScript? Also elucidate the drawbacks of using the timer, if any?",
"Which symbol is used for comments in Javascript?",
"What is the difference between ViewState and SessionState?",
"What is === operator?",
"Explain how can you submit a form using JavaScript?",
"Does JavaScript support automatic type conversion?",
"How can the style/class of an element be changed?",
"Explain how to read and write a file using JavaScript?",
"What are all the looping structures in JavaScript?",
"What is called Variable typing in Javascript?",
"How can you convert the string of any base to integer in JavaScript?",
"Explain the difference between \"==\" and \"===\"?",
"What would be the result of 3+2+\"7\"?",
"Explain how to detect the operating system on the client machine?",
"What do mean by NULL in Javascript?",
"What is the function of delete operator?",
"What is an undefined value in JavaScript?",
"What are all the types of Pop up boxes available in JavaScript?",
"What is the use of Void(0)?",
"How can a page be forced to load another page in JavaScript?",
"What is the data type of variables of in JavaScript?",
"What is the difference between an alert box and a confirmation box?",
"What are escape characters?",
"What are JavaScript Cookies?",
"Explain what is pop()method in JavaScript?",
"Whether JavaScript has concept level scope?",
"Mention what is the disadvantage of using innerHTML in JavaScript?",
"What is break and continue statements?",
"What are the two basic groups of dataypes in JavaScript?",
"How generic objects can be created?",
"What is the use of type of operator?",
"Which keywords are used to handle exceptions?",
"Which keyword is used to print the text in the screen?",
"What is the use of blur function?",
"What is variable typing?",
"How to find operating system in the client machine using JavaScript?",
"What are the different types of errors in JavaScript?",
"What is the use of Push method in JavaScript?",
"What is unshift method in JavaScript?",
"What is the difference between JavaScript and Jscript?",
"How are object properties assigned?",
"What is the 'Strict' mode in JavaScript and how can it be enabled?",
"What is the way to get the status of a CheckBox?",
"How can the OS of the client machine be detected?",
"Explain window.onload and onDocumentReady?",
"How will you explain closures in JavaScript? When are they used?",
"How can a value be appended to an array?",
"Explain the for-in loop?",
"Describe the properties of an anonymous function in JavaScript?",
"What is the difference between .call() and .apply()?",
"Define event bubbling?",
"Is JavaScript case sensitive? Give an example?",
"What boolean operators can be used in JavaScript?",
"How can a particular frame be targeted, from a hyperlink, in JavaScript?",
"What is the role of break and continue statements?",
"Write the point of difference between web-garden and a web-farm?",
"How are object properties assigned?",
"What is the method for reading and writing a file in JavaScript?",
"How are DOM utilized in JavaScript?",
"How are event handlers utilized in JavaScript?",
"Explain the role of deferred scripts in JavaScript?",
"What are the various functional components in JavaScript?",
"Write about the errors shown in JavaScript?",
"What are Screen objects?",
"Explain the unshift() method ?",
"Define unescape() and escape() functions?",
"What are the decodeURI() and encodeURI()?",
"Why it is not advised to use innerHTML in JavaScript?",
"What does the following statement declares?",
"How are JavaScript and ECMA Script related?",
"What is namespacing in JavaScript and how is it used?",
"How can JavaScript codes be hidden from old browsers that don't support JavaScript?"]


behavioral_questions = [
"Describe a situation when you did much more than it was expected from you to get the project done. Were your efforts recognized? By whom and how? How did that make you feel?",
"Tell me about a time when you took ownership of a project. Why did you do this? What was the result of you taking the challenge? What could have happened if you did not take ownership?",
"Think about an instance in which you came up with a project idea that was implemented primarily because of your efforts. What was it about? What was its outcome? What was your role?",
"Describe a time when you made a suggestion to improve something on the project that you were working on.",
"Give me an example of the project or initiative that you started on your own. It can be a non-business one. What prompted you to get started?",
"Describe a situation in which you met a major obstacle in order to complete a project. How did you deal with it? What steps did you take?",
"Tell me about a time you had to work on several projects at once. How did you handle that?",
"Describe a situation in which you have experienced a significant project change that you weren’t expecting. What was it? How did that impact you, and how did you adapt to this change? How did you remain productive through the project?",
"Describe a situation in which you had to adjust to changes over which you had no control. How did you do this?",
"I’d be interested in hearing about a miscommunication you had with your supervisor. How did you solve it? What was the reason for that? How did you deal with that situation?",
"Tell me about an instance when you had to communicate a really bad piece of news to your supervisor or team members. How did you handle it? What was the outcome?",
"Provide an example of a time when you didn’t agree with other programmers. Did you stand up for something that you believed was right?",
"Tell me about a time when you had to present a complex programming problem to a person that didn’t understand technical jargon. How did you ensure that the other person understood you?",
"Describe a situation in which you felt you had not communicated well enough. What did you do? How did you handle it?",
"Tell me about a situation that you had to speak up and be assertive in order to get a point across that was important for you.",
"Tell me about a time when you had a disagreement with another programmer. How did you handle the situation? Were you able to reach a mutually beneficial resolution to that conflict? If not, why were you and your co-worker unable to reach a mutually beneficial resolution? If you knew then what you know now, what would you have done differently to either prevent the conflict, or to resolve it?",
"Tell me about a time when you had to work with a difficult person to accomplish a goal. What was the biggest challenge? How did you handle it?",
"Has there been a time on a project when you disagreed with someone? What did you do about it?",
"Tell me about when you had to deal with conflict within your team. How was the conflict solved? How did you handle that? How would you deal with it now?",
"Give me an example of a time you had to take a creative and unusual approach to solve a coding problem. How did this idea come to your mind? Why do you think it was unusual?",
"Give me an example of a time when you were faced with a complex project related matter and you could not decide on the best way to deal with it. What did you do? How did you go about making the decision – lead me through your decision process? If you could make the decision once again, would you change anything",
"Think about an instance in which you made a decision at work that was unpopular. How did you handle it?",
"Give me an example of a project that completely failed. Why do you think it was a failure? Could there be anything done differently in order to turn it into success?",
"Describe a situation in which you worked diligently on a project and it did not produce the desired results. Why didn’t you get the desired results? What did you learn from the experience?",
"Think about a situation when you made a poor decision or did something that just didn’t turn out right. What happened?",
"Provide an example of an important project goal you reached and how you achieved it.",
"Think about an instance in which you worked on and achieved multiple project goals.",
"Describe a circumstance when you were not able to achieve a project goal that was set by your supervisor. How did you handle this situation? What was the outcome?",
"Think about an instance in which you had to depend on others to help you achieve a project goal. How did you feel?",
"Tell me about a recent situation at work in which you were able to convince management to accept one of your ideas.",
"Describe a situation in which you experienced difficulty in getting others to accept your ideas? What was your approach? How did this work? Were you able to successfully persuade someone to see things your way?",
"Have you ever had to “sell” an idea to your project team? How did you do it? Did they “buy” it?",
"Tell me about a situation when you were responsible for project planning. Did everything go according to your plan? If not, then why and what kind of counteractions did you have to take?",
"Tell me about a situation when you were responsible for project planning. Did everything go according to your plan? If not, then why and what kind of counteractions did you have to take?",
"Tell me about a situation when you made a mistake at work. What happened exactly and how did you deal with it? What steps did you take to improve the situation?",
"What is the biggest problem you have faced on projects so far and how did you solve it? What made the problem difficult to resolve? What was the result? Would you do anything differently now?",
"Give me an example of a time when you noticed a small problem before it turned into a major one. Did you take the initiative to correct it? What kind of preventive measure did you undertake?",
"Walk me through a difficult/complex problem/project you encountered. How did you decide what to do first? What information did you need? What obstacles did you face? Which ones were you able to overcome? Did you have to ask for help?",
"Tell me about a time when you worked with someone who was not completing his or her share of the work. How did you handle the situation? Did you discuss your concern with your coworker? With your manager? If yes, how did your coworker respond to your concern? What was your manager’s response?",
"Describe a situation where you had to work in a team that didn’t get on very well. What happened? What did you do and what role did you take? How did the situation evolve?",
"Describe a team experience you found disappointing. What would you have done differently to prevent this?",
"Give me an example of working cooperatively as a team member to accomplish an important goal. What was the objective? To what extent did you interact with other project members?",
"Tell me about the most difficult situation you have had when leading a team. What happened and how did you handle it? Were you successful? What was the most important thing you did?",
"Describe a situation when you worked effectively under pressure. How did you feel when working under pressure? What was going on, and how did you get through it?",
"Tell me about a situation when you had problems working under pressure. How did you handle that situation? Did you decide to ask for support? How and when did you ask for help?",
"Give me a recent example of a stressful situation on the job. What happened? How did you handle it?" ]



ruby_questions.each do |q|
  Question.create(body: q, category: 'ruby')
end

javascript_questions.each do |q|
  Question.create(body: q, category: 'javascript')
end

behavioral_questions.each do |q|
  Question.create(body: q, category: 'behavioral')
end



